### ISSUE TITLE
I have got an error.

### ISSUE THREAD

**Issue by kotenok2000** [ArchiveTeam/terroroftinytown#81]
Skipping tasks for this item.
Starting CheckIP for Item 
Finished CheckIP for Item 
Starting RunScraper for Item 
Getting item from tracker.
INFO:terroroftinytown.client.tracker:Contacting tracker.
Error communicating with tracker: 404 Client Error: No free items available currently. Don't worry; this is normal. You will be assigned items soon. for url: https://tracker.archiveteam.org:1338/api/get.
Trying again in 11 seconds.
INFO:terroroftinytown.client.tracker:Contacting tracker.
Error communicating with tracker: 404 Client Error: No free items available currently. Don't worry; this is normal. You will be assigned items soon. for url: https://tracker.archiveteam.org:1338/api/get.
Trying again in 79 seconds.
INFO:terroroftinytown.client.tracker:Contacting tracker.
Error communicating with tracker: 404 Client Error: No free items available currently. Don't worry; this is normal. You will be assigned items soon. for url: https://tracker.archiveteam.org:1338/api/get.
Trying again in 47 seconds.
INFO:terroroftinytown.client.tracker:Contacting tracker.
Error communicating with tracker: 404 Client Error: No free items available currently. Don't worry; this is normal. You will be assigned items soon. for url: https://tracker.archiveteam.org:1338/api/get.
Trying again in 66 seconds.
INFO:terroroftinytown.client.tracker:Contacting tracker.
Error communicating with tracker: 404 Client Error: No free items available currently. Don't worry; this is normal. You will be assigned items soon. for url: https://tracker.archiveteam.org:1338/api/get.
Trying again in 140 seconds.
INFO:terroroftinytown.client.tracker:Contacting tracker.
Error communicating with tracker: 404 Client Error: No free items available currently. Don't worry; this is normal. You will be assigned items soon. for url: https://tracker.archiveteam.org:1338/api/get.
Trying again in 96 seconds.
Traceback (most recent call last):
  File "/home/warrior/data/projects/urlteam2-b9421f4/terroroftinytown/terroroftinytown/client/tracker.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/home/warrior/data/projects/urlteam2-b9421f4/terroroftinytown/terroroftinytown/client/tracker.py", line 67, in get_item
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: No free items available currently. Don't worry; this is normal. You will be assigned items soon. for url: https://tracker.archiveteam.org:1338/api/get

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/warrior/data/projects/urlteam2-b9421f4/scraper.py", line 78, in <module>
    main()
  File "/home/warrior/data/projects/urlteam2-b9421f4/scraper.py", line 34, in main
    item_info = try_with_tracker(tracker_client.get_item)
  File "/home/warrior/data/projects/urlteam2-b9421f4/scraper.py", line 62, in try_with_tracker
    return func(*args, **kwargs)
  File "/home/warrior/data/projects/urlteam2-b9421f4/terroroftinytown/terroroftinytown/client/tracker.py", line 30, in wrapper
    six.raise_from(TrackerError(str(error)), error)
  File "<string>", line 2, in raise_from
terroroftinytown.client.tracker.TrackerError: 404 Client Error: No free items available currently. Don't worry; this is normal. You will be assigned items soon. for url: https://tracker.archiveteam.org:1338/api/get
Process RunScraper returned exit code 1 for Item 
Failed RunScraper for Item 
Waiting 10 seconds...

**Comment by kotenok2000** [comment]
It is  "waiting 10 seconds" for 20 minutes
